parameters:
    app.sender_email: '%env(MAILER_SENDER)%'
    app.sender_name: '%env(MAILER_SENDER_NAME)%'
    gemini_api_key: '%env(GEMINI_API_KEY)%'
    gemini_upload_dir: '%kernel.project_dir%/public/uploads/produits'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\EmailService:
        arguments:
            $senderEmail: '%app.sender_email%'
            $senderName: '%app.sender_name%'
    App\Service\GeminiService:
        arguments:
            $apiKey: '%gemini_api_key%'
            $uploadDir: '%kernel.project_dir%/public/uploads/produits%'
    App\Service\GroqService:
        arguments:
            $apiKey: '%env(GROQ_API_KEY)%'
            $uploadDir: '%kernel.project_dir%/public/uploads/produits'
    App\Service\ImportBackupService:
        arguments:
            $projectDir: '%kernel.project_dir%'
