parameters:
    app.sender_email: '%env(MAILER_SENDER)%'
    app.sender_name: '%env(MAILER_SENDER_NAME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\EmailService:
        arguments:
            $senderEmail: '%app.sender_email%'
            $senderName: '%app.sender_name%'
