parameters:
    ai_upload_dir: '%kernel.project_dir%/public/uploads/produits'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $uploadDir: '%ai_upload_dir%'
            string $projectDir: '%kernel.project_dir%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\GeminiService:
        arguments:
            $apiKey: '%env(GEMINI_API_KEY)%'

    App\Service\GroqService:
        arguments:
            $apiKey: '%env(GROQ_API_KEY)%'